### ISSUE TITLE
Map Layer

### ISSUE THREAD

**Issue by rjcc88** [putteabrahamsson/react-native-leaflet-ts#11]
map are not showing

this are my current layer
![map](https://user-images.githubusercontent.com/53323673/219312723-a0e7fd6e-067b-42ea-8192-4594696c6d0d.png)

**Comment by putteabrahamsson** [comment]
Which version are you using? 

I can try this a bit later & see. Everything worked fine for me when I tested it yesterday. :)

**Comment by putteabrahamsson** [comment]
https://server.arcgisonline.com/ArcGIS/rest/service/World_Imagery/MapServer/tile/{z}/{y}/{x}.png 
**is not working for me.**

https://{s}.tile.openstreetmap.de/{z}/{x}/{y}.png
**is working for me**

Make sure you set the version to "0.2.16" without "^" and then "yarn / npm i" and "cd ios && pod install" and then re-run the app.

**Comment by rjcc88** [comment]
@putteabrahamsson  this the current version im using but still no response from map still green
![version](https://user-images.githubusercontent.com/53323673/219333793-930f9a35-66a8-432d-ba3e-2bd8b075c57a.png)

**Comment by rjcc88** [comment]
this only shows at my project

![Screenshot_1676547225](https://user-images.githubusercontent.com/53323673/219354010-8cb13c14-d5e2-4b35-9fff-5fa2c1ed3e90.png)

**Comment by putteabrahamsson** [comment]
Perhaps some Android bug then. I will try to look into this and see the result

**Comment by putteabrahamsson** [comment]
@rjcc88 Can you send the full code?

**Comment by rjcc88** [comment]
import React, { useState } from "react";
import {
  SafeAreaView,
} from "react-native"
import { AppRootStackParamList } from "@/Route/app/app-navigator";
import { NativeStackScreenProps } from '@react-navigation/native-stack'

import { DOMParser } from '@xmldom/xmldom'
import { kml } from "@tmcw/togeojson";
import Leaflet, { Markers, TileOptions, Layers, GeoJson, GeoJsonFeatures } from 'react-native-leaflet-ts';

type Props = NativeStackScreenProps<AppRootStackParamList, 'Map'>;

const Map = ({ navigation: { navigate } }: Props) => {
  const coords: GeoJson = {
    type:'',
    features:[{
      type:'',
      geometry:{
        type:'',
        coordinates:[]
      }
    }]
  }
  React.useEffect(() => {
    fetch(
      "https://gist.githubusercontent.com/wf9a5m75/7785aaef59e46bcb6159ffa5a5feb437/raw/ad2487fac5d2e865a7189a239208f344c0fc3d32/sample.kml"
    )
      .then((res) => res.text())
      .then((kmlText) => {
        const parser = new DOMParser();
        const kmls = parser.parseFromString(kmlText, "text/xml");

        const routes = kml(kmls)
          coords.type = routes.type
        routes.features.map((res: any) => {
      
        coords.features = res
         
        })

        console.log(coords)
      });
  }, []);


  const sample: GeoJsonFeatures={
    type:'',
    geometry:{
      type:'',
      coordinates:[]
    }
  }
  const options: TileOptions = {
    noWrap: true,
    detectRetina: true,
    tileSize: 200,
    keepBuffer:2,
    zIndex:1
  };

  const mapLayers: Layers[] = [
    {
      name: 'Arc GIS',
      src: 'http://maps.wikimedia.org/osm-intl/{z}/{x}/{y}.png',
      tileOptions: options,
    },
    {
      name: 'Open Street',
      src: 'https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',
      tileOptions: options,
    },
    {
      name: 'Open Street',
      src: 'https://server.arcgisonline.com/ArcGIS/rest/services/World_Imagery/MapServer/tile/{z}/{y}/{x}',
      tileOptions: options,
    },

  ];


  return (
    <SafeAreaView className="flex absolute inset-0 justify-center">

      <Leaflet
        mapLayers={
          mapLayers
        }
        minZoom={1}
        zoom={2}
        maxZoom={6}
        flyTo={{
          latLng: [-38.31571580761326, -23.735463483398522],
          zoom: 5,
        }}
        // geoJson={coords}
        // backgroundColor="green"
      />

    </SafeAreaView>
  )
}
export default Map;

**Comment by rjcc88** [comment]
> Perhaps some Android bug then. I will try to look into this and see the result

maybe it has, i try to change different types of maps at my array it still has no response

**Comment by putteabrahamsson** [comment]
This issue is now fixed for Android aswell.

Please update to version:
`"react-native-leaflet-ts": "0.2.18",`
And make sure you run "yarn / npm install" and "cd ios && pod install"

I tried with an android emulator and works fine now. However, your first map is still not accessible. But the second one: "https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png" is working correctly.

Thanks!
