### ISSUE TITLE
do markers update with the tile?

### ISSUE THREAD

**Issue by loloide** [putteabrahamsson/react-native-leaflet-ts#13]
I am trying to show the location of something that moves through the map.
the coords arrive via socket.io but the map doesn't render when the markers are added to the array (the array starts empty but it then gets objects from the socket.io)

i thought that having `updateInterval` on `TileOptions` would do it but turns out it wasn't the case.

maybe a solution would be to call the function to draw the markers with the `updateInterval`?

thanks

**Comment by putteabrahamsson** [comment]
I'll look into this asap.
If you have time contributing that'd be perfect! :)

**Comment by loloide** [comment]
sure, i'll try to get the call thank you

**Comment by loloide** [comment]
hi, im also trying to use the `flyTo` function to pan the map to different coords after it loads
so today im trying to do both things

**Comment by putteabrahamsson** [comment]
Oki! I'll try to fix asap.

**Comment by loloide** [comment]
so today i found a way to do the markers thing
in the `node_modules/react-native-leaflet-ts/src/Leaflet/index.tsx` file, i added an interval for the sendAction of the markers
it now looks like this:
`setInterval(() => {
      if (markers) sendAction({ markers });
    }, 100)`

but the issue now is deleting them, i was trying to use `map.removeLayer()` with a `setTimeout()` on `/node_modules/react-native-leaflet-ts/android/src/main/assets/Leaflet.html` but it didn't work.

i want to remove the existing markers because if the thing im tracking moves, the markers end up making a trail instead of showing its current location

**Comment by loloide** [comment]
i managed to resolve the flyto part using `useState` and `useEffect`. 
i think i can do the same thing with the markers.

by the way, i think you should change `injectJavascript` from `string` to `void` when you declare the props since you are going to run a script. having it on `string` will throw an error saying that it expects a string, not `void`. :)

**Comment by putteabrahamsson** [comment]
Nice! I'll look into it!
