### ISSUE TITLE
Improvements

### ISSUE THREAD

**Issue by M-Jeremy** [putteabrahamsson/react-native-leaflet-ts#16]
Proposing some improvements : 
- Adding "attribution" attribute to mapLayer
- Triggering flyTo programmatically, like : 
<img width="344" alt="Screenshot 2023-08-24 at 14 14 35" src="https://github.com/putteabrahamsson/react-native-leaflet-ts/assets/81267136/2021edbd-c9fd-4b9d-824f-c60e1f44333c">

- Android bug :
![Screenshot 2023-08-24 at 14 18 32](https://github.com/putteabrahamsson/react-native-leaflet-ts/assets/81267136/6d163a49-739d-42ac-932f-6f675c25c897) 
see fix -> https://github.com/pavel-corsaghin/react-native-leaflet/issues/8#issuecomment-1435787897

- Clustering markers
- Custom marker popup

**Comment by putteabrahamsson** [comment]
Thanks!
I'll look into this asap!

**Comment by putteabrahamsson** [comment]
* Added ref to programmatically trigger flyTo and clearMarkers.
* Added attribution
* Fixed android issue
