### ISSUE TITLE
Custom Icon

### ISSUE THREAD

**Issue by franbusleiman** [putteabrahamsson/react-native-leaflet-ts#17]
Hi, do you know if there's a way of creating a custom icon for the markers? I mean using html or a react component. 
Thanks in advance!

**Comment by putteabrahamsson** [comment]
Hey!
There should be some way, but not sure if that's broken. I'll try to find time during this week to implement it otherwise.👍🏼

**Comment by franbusleiman** [comment]
Thank you!

**Comment by franbusleiman** [comment]
Hi @putteabrahamsson, do you think there's a solution?

**Comment by guo519300884** [comment]
> Hi @putteabrahamsson, do you think there's a solution?

Hi, I'm developing maps with ReactNative,can you refer to your demo?
Thank you in advance.

**Comment by putteabrahamsson** [comment]
Implemented in v0.3.3
