### ISSUE TITLE
mapLayers props

### ISSUE THREAD

**Issue by mughniaziz004** [putteabrahamsson/react-native-leaflet-ts#18]
What do i'm input in src mapLayers props ?

look like https://maps.google.com/maps?q=${location?.latitude},${location?.longitude}&z=35&radius=100 ?

because i'm implemented this package the map cannot be shown

**Comment by putteabrahamsson** [comment]
The map has to contain X, Y & Z coordinates. 

Just like the map below (do not add your own values to z, x and y. This is handled automatically):

https://cdn.myIndoorMap.com/maps/0faebe50-19e5-4445-9177-a09903973304/rev0/{z}/{x}/{-y}.png
