### ISSUE TITLE
Show attribution in the map

### ISSUE THREAD

**Issue by marcodemutti** [putteabrahamsson/react-native-leaflet-ts#19]
Hi @putteabrahamsson! 

First of all thank you for your work. 
I am trying to use your repo in my expo/react native project and I would like to be able to show the attribution at the bottom-right corner of the view, as in other libraries like this one: https://github.com/pavel-corsaghin/react-native-leaflet.
I think at the current stage it is not possible with your library. If this is the case, I would suggest considering adding this feature.
In the meantime, could you give me some hint on how to do it myself?

Thank you!

**Comment by putteabrahamsson** [comment]
Hello! Let me check and i'll get back to you. 

Thanks! :)

**Comment by putteabrahamsson** [comment]
im looking into this now. sorry for the delay. 
what exactly do you want to show? @marcodemutti

**Comment by putteabrahamsson** [comment]
Added now, will push soon.
