### ISSUE TITLE
Works only if react-native-webwiew is installed

### ISSUE THREAD

**Issue by jsiot76** [putteabrahamsson/react-native-leaflet-ts#4]
Hi, 
installation of react-native-webwiew is needed, else the following error is raised.
Sounds like a lack of dependency ?

Regards, Jérome

Error:
-------------------------------------------------
ERROR  TypeError: null is not an object (evaluating '_reactNative.NativeModules.RNCWebView.isFileUploadSupported')
ERROR  Invariant Violation: Module AppRegistry is not a registered callable module (calling runApplication). A frequent cause of the error is that the application entry file path is incorrect.
     This can also happen when the JS bundle is corrupt or there is an early initialization error when loading React Native.
ERROR  Invariant Violation: Module AppRegistry is not a registered callable module (calling runApplication). A frequent cause of the error is that the application entry file path is incorrect.
     This can also happen when the JS bundle is corrupt or there is an early initialization error when loading React Native.
-------------------------------------------------

my package.json :

{
    "name": "test",
    "version": "0.0.1",
    "private": true,
    "scripts": {
      "android": "react-native run-android",
      "ios": "react-native run-ios",
      "start": "react-native start",
      "test": "jest",
      "lint": "eslint ."
    },
    "dependencies": {
      "@react-native-async-storage/async-storage": "^1.17.3",
      "@rneui/base": "^4.0.0-rc.1",
      "@rneui/themed": "^4.0.0-rc.1",
      "moment": "^2.29.2",
      "react": "17.0.2",
      "react-native": "0.68.0",
      "react-native-get-location": "^2.2.1",
      "react-native-leaflet-ts": "^0.2.11",
      "react-native-safe-area-context": "^4.2.4",
      "react-native-splash-screen": "^3.3.0",
      "react-native-vector-icons": "^9.1.0",
      "react-native-webview": "^11.25.0"  ============================> needed
    },
    "devDependencies": {
      "@babel/core": "^7.12.9",
      "@babel/runtime": "^7.12.5",
      "@react-native-community/eslint-config": "^2.0.0",
      "babel-jest": "^26.6.3",
      "eslint": "^7.32.0",
      "jest": "^26.6.3",
      "metro-react-native-babel-preset": "^0.67.0",
      "react-test-renderer": "17.0.2"
    },
    "jest": {
      "preset": "react-native"
    }
  }

**Comment by putteabrahamsson** [comment]
I'll look into it asap. But yeah, webview might be needed until I patch the dependency.

Thanks!

**Comment by putuoka** [comment]
> I'll look into it asap. But yeah, webview might be needed until I patch the dependency.
> 
> Thanks!

could you please add example folder for newbie like me to easier to understand what should it looks when running successfully

**Comment by putteabrahamsson** [comment]
Sure, I can do that!

**Comment by putuoka** [comment]
> Sure, I can do that!

btw i have successfully running some test with this repo and it's very slow compare to rnmapbox. i think the webview isn't good for this. i'm trying to create cluster map with 1000 coordinates lat,long list from json

**Comment by putteabrahamsson** [comment]
Dependency should be fixed now.
