### ISSUE TITLE
Multiple Layers

### ISSUE THREAD

**Issue by rjcc88** [putteabrahamsson/react-native-leaflet-ts#8]
Please Enable Multiple map layers

**Comment by putteabrahamsson** [comment]
I'll see what I can do! :)

**Comment by putteabrahamsson** [comment]
Might be released soon! 
Currently working on it!

**Comment by putteabrahamsson** [comment]
Added

**Comment by rjcc88** [comment]
thanks a lot really appreciated this library it will help a lot to me. I will contribute soon as my project done. well done and great Job
